RAINBOW_FLAG = '\N{WAVING WHITE FLAG}\N{VARIATION SELECTOR-16}\N{ZWJ}\N{RAINBOW}'
TRANS_FLAG = (
    '\N{WAVING WHITE FLAG}\N{VARIATION SELECTOR-16}\N{ZERO WIDTH JOINER}'  # Trans flag
    '\N{MALE WITH STROKE AND MALE AND FEMALE SIGN}\N{VARIATION SELECTOR-16}'
)

TEST_STRING = f'{RAINBOW_FLAG} We love our friends {TRANS_FLAG}'
