name: Tests

permissions:
  contents: read

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/test.yml"
      - "src/nandict/**"
      - "tests/**"
      - "pyproject.toml"
  pull_request:
    paths:
      - ".github/workflows/test.yml"
      - "src/nandict/**"
      - "tests/**"
      - "pyproject.toml"

jobs:
  test-against-python-matrix:
    name: PyTest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14", "3.15"]
        os: [ windows-latest, macos-latest, ubuntu-latest ]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@a9b33f02405f50e505f17ab8530e42a23200a5d1
        with:
          enable-cache: true
      - name: Run tests
        run: |
          uv run -p ${{ matrix.python-version }} pytest
