name: GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/test.yml"
  pull_request:
    branches: ["**"]
    paths:
      - ".github/workflows/test.yml"

permissions: {}

jobs:
  zizmor:
    name: Run zizmor 🌈
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required for upload-sarif (used by zizmor-action) to upload SARIF files.
      contents: read         # Only needed for private repos. Needed to clone the repo.
      actions: read          # Only needed for private repos. Needed for upload-sarif to read workflow run info.
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@40b41b824eab0ad9c19ddf9856be25550729e6d8
